### ISSUE TITLE
Isotope patter overlay

### ISSUE THREAD

**Issue by michelleting** [larsyunker/mass-spec-python-tools#23]
I tried running the script with the both your file in the validation folder and with my data but the output figure would only show the mass peak but not the isotope patter bars. see attached pics. The Ar-I+ figure doesn't even have the isotope pattern bars. Wondering what is going on...? 

@Line 424 of molecule.py (out[0].append(x))
BAR
x = [479.04256000000004, 480.04594086958247, 481.04927, 482.052625]
y = [100.0, 27.280848507524876, 3.509399355066259, 0.24494730118962427]
Automatically determining m/z window: 477 - 482

@Line 927 of tome.py (ax.bar)
AXBAR
simdict[species]['x'] = [479.04256000000004, 480.04594086958247, 481.04927, 482.052625]
simdict[species]['y'] = [0.4452669723598899, 0.12147260818354422, 0.015626196256321032, 0.0010906694318843005]

**Comment by larsyunker** [comment]
The calibration of the included mzML file is particularly bad (off by _m/z_ ~0.25), so the auto-scaling of peak heights is normalizing the predicted isotope pattern to a near-zero value. The user can override this functionality by changing `'simnorm'` to `100` (or another value of their choice). The resulting patterns look like this: 
![LY-2015-09-15 06 (summed spectra (scans 1-2576)) Ar+I](https://user-images.githubusercontent.com/19736507/54239169-a5b0de00-44d7-11e9-815b-36c78ed81a4d.png)
![LY-2015-09-15 06 (summed spectra (scans 1-2576)) L2PdAr+I](https://user-images.githubusercontent.com/19736507/54239171-a5b0de00-44d7-11e9-8494-b2317b559056.png)

**Comment by michelleting** [comment]
Hi Lars, 
I updated the whole project with github desktop but with this extra line in molecule.py (see below), the script wouldn't run and make an isotope overlay figure. I ended up deleting this line from molecule.py but I wonder if deleting it would affect another script. Thanks.

`from IsoSpecPy.IsoSpecPy import IsoSpec`

**Comment by larsyunker** [comment]
You will need to rerun setup (`python setup.py install`) because there is a new dependency.
