### ISSUE TITLE
PyRSIR errors out

### ISSUE THREAD

**Issue by tanoury1** [larsyunker/mass-spec-python-tools#29]
Hi Lars,
I started working with PyRSIR and ran into a few issues:
1.  PyRSIR does not automatically load the files in lines 46 and 49, nor does it read the working directory.  I get a "Directory:" prompt and file name prompts.  Is this expected behavior?
2.  After enter directory and file names, PyRSIR errors out.  I the output is below.

runfile('C:/Program Files/PythoMS-master/PyRSIR.py', wdir='C:/Program Files/PythoMS-master')
Reloaded modules: pythoms, pythoms.tome, pythoms.spectrum, pythoms.colour, pythoms.molecule, pythoms.scripttime, pythoms.progress, pythoms.mass_dictionaries, pythoms.mass_abbreviations, pythoms.mzml, pythoms.psims, pythoms.xlsx
Data was read from PSI-MS, please cite DOI: 10.1093/database/bat009

Directory: /Program Files/PythoMS-master/validation_files

Raw or mzML filename: LY-2015-09-15_06.mzML

Excel file name: pyrsir_validation.xlsx

Scans to bin (separate multiple values with commas): 3
Start time: 05:38:06 PM
Loading workbook "/Program Files/PythoMS-master/validation_files\pyrsir_validation.xlsx" into memory DONE
 DONE
Loading /Program Files/PythoMS-master/validation_files\LY-2015-09-15_06.mzML into memory DONE
Estimating resolution of the instrument 100.0% DONE
Traceback (most recent call last):

  File "<ipython-input-10-463b1844b2cd>", line 1, in <module>
    runfile('C:/Program Files/PythoMS-master/PyRSIR.py', wdir='C:/Program Files/PythoMS-master')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Program Files/PythoMS-master/PyRSIR.py", line 445, in <module>
    pyrsir(filename, xlsx, n)

  File "C:/Program Files/PythoMS-master/PyRSIR.py", line 326, in pyrsir
    sp = prepformula(sp)

  File "C:/Program Files/PythoMS-master/PyRSIR.py", line 230, in prepformula
    if mzml.functions[fn]['type'] == 'MS':

KeyError: 4

Jerry

**Comment by larsyunker** [comment]
Hi Jerry,
I will look into this tomorrow. Would it be possible to share the mzML file in question? With only a brief look at the traceback it seems that the script is looking for a spectrum that isn't present, which is... Curious.

**Comment by tanoury1** [comment]
Hi Lars,
I gunzipped the LY....MZml.gz file that was in the validation_files
diretory and used the attached xlms file.

Jerry

**Comment by larsyunker** [comment]
Hi Jerry, 

I think I understand now. The xlsx you were trying to use does not match the configuration of the mzML you had targetted (the script was expecting additional functions and modes which are not present in the single-function mzML you had targetted). I have renamed the excel file to hopefully clarify the confusion. I have also added another PySIR example xlsx which pairs with `LY-2015-09-15.mzML.gz`. 

Another feature of the `mzML` class is reading gzipped files, so you do not need to unzip the mzML file.

**Comment by tanoury1** [comment]
Hi Lars,
Thank you so much!  It is nice to have all the pieces for a test case so
the user (me) can gain some experience using your code for something that
will work. I'll give it a go asap.  I may be getting in touch with you
again once I start using my own data.

Best regards,
Jerry

**Comment by tanoury1** [comment]
Hi Lars,
PyRSIR worked.  However, even though I had the mzML.gz and .xlsx files
entered in lines 46 and 49, I got a "Directory:" prompt requiring me to
enter the directory that contained the mzML.gz and .xlsx files.  I then got
a "Raw or mzML filename:" , "Excel file name:" and "Scans to bin (separate
multiple values with comments):" prompts to add the appropriate
information.  For me, that is fine.  This allows me to run it from command
line.

I would like to polish the look of the plots that are printed after the run
completes.  The title to the Summation plot overlaps with the x-axis of the
Raw Data plot, and there is no legend.  Which line belongs to which
species.  Where do I find the code that defines the plotting?  Or, if you
are able to add that easily?????

Thanks so much for the help,
Jerry

**Comment by larsyunker** [comment]
Hi Jerry, 
Sorry the prompting is a legacy thing from how I used to execute scripts. If the script is "run" instead of executed in a Python interpreter the file paths specified in the script are ignored. Command line arguments should be supported, as you've found. 

The plots are generated in the `plots` sub-function of `pyrsir` (line `95` of the script). You can tweak them as you see fit. It is a `matplotlib` plot with subplots. I had found that I almost always did extra processing in excel after the fact and usually plotted from that data rather than the raw output of `pyrsir`. This is why the output plot is so poorly laid out. For naming and interpreting within the `pyrsir` function, all the data is contained within the `sp` dictionary. That dictionary is composed of subdictionaries for each key provided in the excel file (the keys of `sp` are the names defined).

**Comment by tanoury1** [comment]
Thank you Lars. The command line approach for pyrsir is fine.

All the best
Jerry
